### ISSUE TITLE
No Icon for Policy Initiative (aka PolicySetDefinition)

### ISSUE THREAD

**Issue by rwsanders** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#10]
Maybe there is an icon, but it is labeled something other than what I would expect.  I'm looking for the icon used for Policy Initiatives (a.k.a.  Set Definitions).

**Comment by sandroasp** [comment]
There is no "official" Policy Initiatives or Set Definitions but you can use the Policy shape present in the MIS Security and Governance
