### ISSUE TITLE
Missing Azure Stream Analytics in IoT stencil

### ISSUE THREAD

**Issue by rploeg** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#11]
I would expect Azure Stream Analytics in the IoT Stencil. I don't see it also in the other stencil. Maybe good idea to add them to the IoT stencil because it's an important part of IoT.

Great job!

**Comment by ManuInNZ** [comment]
It is present. Looks further.
Green logo from memory

**Comment by sandroasp** [comment]
The Azure Stream Analytics is on the Azure MIS Azure Stencils.vssx resource.
I add it also on the IoT stencil and update the stencils.
