### ISSUE TITLE
Updated and correct icon for DevTest Labs?

### ISSUE THREAD

**Issue by yaegashi** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#13]
Hi, thanks for the great stencil collection.

I'm looking for an SVG for the new DevTest Lab icon seen in the Azure Portal as follows:

![image](https://user-images.githubusercontent.com/106724/72053012-8f4afd00-3309-11ea-9f6a-68cdfab20232.png)

But current SVG in the repository looks like the older icon.  Could you update this file?

![image](https://user-images.githubusercontent.com/106724/72054240-f1a4fd00-330b-11ea-94a1-56d754d92941.png) https://github.com/sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio/blob/master/Others/SVG/Developer/DevTest%20Labs.svg

Also, the product pages for DevTest Labs and Lab Services show different icons than in the Azure Portal.  I suppose they're the same as ones found in https://azure.microsoft.com/ja-jp/patterns/styles/glyphs-icons/.  Which icon is correct for DevTest Labs?

[![image](https://user-images.githubusercontent.com/106724/72053211-e94bc280-3309-11ea-8203-7c140cec54f1.png)](https://azure.microsoft.com/en-us/pricing/details/devtest-lab/)

[![image](https://user-images.githubusercontent.com/106724/72053299-17310700-330a-11ea-90ef-7696fde63d17.png)](https://azure.microsoft.com/en-us/pricing/details/lab-services/)

**Comment by sandroasp** [comment]
The ones that are correct are in the Azure Portal (the first ones) you may see different icons because it is difficult to update all the documentation I guess :)

I just release a new version that fixed this issue.
