### ISSUE TITLE
DevOps offerings

### ISSUE THREAD

**Issue by jkewley** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#14]
Hey - thanks for these, They are great.

Your developer pack could use a refresh in the Azure DevOps space. It'd be great to have the following icons available:
![image](https://user-images.githubusercontent.com/1148930/73695631-85b67a00-46a8-11ea-9e1d-e0c57b4ab2c9.png)

You might also consider refreshing 'Visual Studio Team Services' and 'DevOps Projects' with the latest (or just updating the names, since the icons are now reversed):

![image](https://user-images.githubusercontent.com/1148930/73695884-05444900-46a9-11ea-9429-46fec8196150.png)

![image](https://user-images.githubusercontent.com/1148930/73695795-dded7c00-46a8-11ea-9183-e04b1ed90fdc.png)

**Comment by sandroasp** [comment]
Hi Josh, can you point me the page (UTL) where I could find these icons. Just to be easier and quite to add them.

**Comment by jkewley** [comment]
Boards
https://cdn.vsassets.io/ext/ms.vss-work-web/common-content/Content/Nav-Plan.XB8qU6v7kvBk_Tcy.png

Repos
https://cdn.vsassets.io/ext/ms.vss-code-web/common-content/Nav-Code.0tJczmQtl3hyKtlh.png

Pipelines
https://cdn.vsassets.io/ext/ms.vss-build-web/common-library/Nav-Launch.3tiJhd8JGiL0mrog.png

Test Plans
https://cdn.vsassets.io/ext/ms.vss-test-web/common-content/Nav-Test.CLbC8LbdE5__mhtfT.png

Artifacts
https://ms.gallerycdn.vsassets.io/extensions/ms/feed/18.162.0.1593194188/1580077585929/common/content/Nav-Feed.png

**Comment by jkewley** [comment]
My screen shot was from within AZDO -> Project Settings -> Overview

**Comment by Huodong-Yuan** [comment]
Cool, I can wait to see they are ready.

**Comment by sandroasp** [comment]
Done, just publish these stencils

![image](https://user-images.githubusercontent.com/1318263/76102277-ad5e7200-5fc7-11ea-8a60-2d89cea3f5ce.png)
