### ISSUE TITLE
Some Azure Icons loose its layout when drag into Visio Diagrams

### ISSUE THREAD

**Issue by irah2008** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#15]
Azure Active Directory icon from Microsoft Azure stencil when i drag it seems loose it layout and turns grey. randomly happening for other icons too
![image](https://user-images.githubusercontent.com/22978615/74415301-11d15a00-4e7e-11ea-80f0-82adcf32f827.png)

**Comment by Huodong-Yuan** [comment]
I have the same issue with Visio Standard 2013 desktop version. But, when I use it with Visio Professional 2019 desktop version, there is no such issue.

**Comment by Mabhex** [comment]
![image](https://user-images.githubusercontent.com/22674413/75512404-093e5f00-59fa-11ea-9398-69b1b3f961ee.png)


I get the same

**Comment by sandroasp** [comment]
What Visio version are you guys using?
It is working fine on my side and I'm using Visio 2019 the only version I have :)

![image](https://user-images.githubusercontent.com/1318263/76097045-efcf8100-5fbe-11ea-986e-4fc3414403f6.png)

**Comment by nbernier** [comment]
I have the same issue on Visio Pro 2016

**Comment by irah2008** [comment]
> What Visio version are you guys using?
> It is working fine on my side and I'm using Visio 2019 the only version I have :)
> 
> ![image](https://user-images.githubusercontent.com/1318263/76097045-efcf8100-5fbe-11ea-986e-4fc3414403f6.png)

Visio Pro 2016

**Comment by zakaluka** [comment]
An easy fix I've found in Visio 2013 is to select the shape (once dragged out onto the canvas) and change the transparency (under Line) from 0% to 100%.  Then, the image will show correctly.

**Comment by dimkdimk** [comment]
Having the same problem in Visio 2016. It seems dependant on Themes. When you choose - No theme, the icons break. The transparency fix by zakaluka works!

**Comment by cybergavin** [comment]
Encountered the same problem (greyed out icons) in Visio Professional 2016. To fix this, you may either change to transparency for Line to 100% as earlier suggested, or simply do the following:

Select icon --> Select shape --> Line --> "No Line" 

(No Line = 100% transparency)

**Comment by robertrichard1beca** [comment]
I selected the "Sequence" theme (where previously there was none) and the problem was solved.
