### ISSUE TITLE
Azure Synapse

### ISSUE THREAD

**Issue by SQLMelody** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#18]
Please consider this a request for Azure Synapse icon.  Thanks!  Appreciate your keeping this up!

**Comment by sandroasp** [comment]
Azure Synapse Analytics is there on Microsoft Azure Stencils
![image](https://user-images.githubusercontent.com/1318263/80590730-5350ba80-8a14-11ea-89f8-549e006960a6.png)
