### ISSUE TITLE
Release mechanism

### ISSUE THREAD

**Issue by ManuInNZ** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#19]
Hi Sandro

Wagner Silveira pointed me to your pack and I am since then a follower 😛 
But AFAIK would be better for you to have a download link button through to TechNet no ?
i.e.  https://gallery.technet.microsoft.com/Collection-of-Integration-e6a3f4d0 

Not that you need more points there but more for the MVP side ?

**Comment by sandroasp** [comment]
Hi Emmanuel,
I do like TechNet Gallery but unfortunately, Microsoft is retiring the TechNet Gallery. So I will only use now GitHub.

**Comment by ManuInNZ** [comment]
Makes sense

So should we just git pull in a way from our 'my shapes'?

Maybe worth proposing a install and update method(scheduled task)?

Cheers

**Comment by sandroasp** [comment]
I add two PowerShell scripts that you can now use to download the latest version and automatically install them.
I hope you like it
