### ISSUE TITLE
Text annotations

### ISSUE THREAD

**Issue by VitalyMCT** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#2]
Is there a recommended way to add captions to these stencils? 

I know we can type in the text with F2 and then use the Text Blob tool to move the text to the bottom of each shape. But this is a manual step that needs to be repeated for each shape.

Thanks,
Vitaly

**Comment by dtjensen** [comment]
Same question as vitaly. The captions are tough to live without.

**Comment by steveculshaw** [comment]
It'd be nice if the standard position was below, rather than on top ... but so many items to change  :-(

**Comment by ravensorb** [comment]
This really is needed to make the stencils useful for documentation :)

**Comment by sandroasp** [comment]
This is being fixed. At least the new one's the Text will be (and are) at the bottom of each shape.

**Comment by marknorrapscm** [comment]
@sandroasp Is this fix still in progress or is it only being applied to new icon sets?

**Comment by derecskey** [comment]
These _look_ fantastic, but are currently unusable.  The text annotation issue is a showstopper.  Is there an update with respect to anticipated delivery date of this feature?

**Comment by sandroasp** [comment]
work in progress, there are many shapes to change and this is a manual process. Fill free to help to expedite this process. Then submit a pull request and I will gladly approve

**Comment by sandroasp** [comment]
All the above issues ARE SOLVED!! yehhhhh

**Comment by steveculshaw** [comment]
Many, many thanks for all the hard work you've done with the Visio stencils Sandro

**Comment by sandroasp** [comment]
Thanks!
