### ISSUE TITLE
Azure Stack icon

### ISSUE THREAD

**Issue by jbpaux** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#21]
Hello,

would be good to have the Azure Stack icon in this new "style". I know it's available as it's in this example: https://docs.microsoft.com/en-us/azure-stack/operator/media/azure-stack-integrate-identity/azure-stack-adfs-architecture.svg?view=azs-2002
Maybe you can extract it :)
Thank you !

**Comment by sandroasp** [comment]
Hi jbpaux,

Add it on MIS Azure Stencils.vssx file
