### ISSUE TITLE
Different default stencils folders depending on Office version

### ISSUE THREAD

**Issue by bramdejager** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#25]
When running the download install PowerShell script the script is not working during copying the files to the final destination. The current script copies the files to "Documents\My Shares". My current Visio install uses the "Documents\Visio Stencils" instead. 

The script should support different destination folder depending on the Office version.

**Comment by cyberjacob** [comment]
Which Office/Visio version do you use?

**Comment by cyberjacob** [comment]
Needs testing on different versions, but this appears to find the relevent key for Visio 365

```powershell
Get-ChildItem HKCU:\Software\Microsoft\Office\ -Recurse | Where-Object {$_.PSChildName -eq "Application"} | Get-ItemProperty -Name MyShapesPath | select MyShapesPath
```

**Comment by sandroasp** [comment]
Thanks for the tip Jacob! just updated the scripts
