### ISSUE TITLE
Lock the aspect ratio of the stencil icons

### ISSUE THREAD

**Issue by HolgerReiners** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#28]
Hello Sandro,

great Visio stencil tool set.

One ask: Could you please set the icon shape property "Protection / LockAspect" =1?
It should be the following Visio Cell property:
LockAspect Cell (Protection Section)
https://docs.microsoft.com/en-us/office/client-developer/visio/lockaspect-cell-protection-section

This would be very hand, as it protects against accidental resizing with another shape aspect.

Thank you!

**Comment by sandroasp** [comment]
Hi Holger Reiners,

I will start doing this, but that will take a lot of time, so it will be an ongoing task for a while

**Comment by sandroasp** [comment]
All the new shapes has this feature enable
