### ISSUE TITLE
Excessive grey border on Availability Sets icon

### ISSUE THREAD

**Issue by softwarecraft** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#29]
Shape _Availability Sets_ in Azure stencil (Azure/SVG/Availability-sets.svg) when added to my Visio 2016 drawing appears as a solid grey blob. When enlarged considerably it is possible to see a solid grey icon border and interior shape border that overlaps when shrunk. By fiddling the icon Line width (setting to 0pt) the icon appears correctly. Please tweak the icon to render correctly without Line width tweak.

**Comment by softwarecraft** [comment]
![Capture](https://user-images.githubusercontent.com/12091402/99452359-6ca64f00-28f1-11eb-842b-f76f837f871a.PNG)

**Comment by netcitizen** [comment]
I find this happening for all icons that i tried in the Azure MIS stencil.

**Comment by cyberjacob** [comment]
Do you know what template you selected when first opening Visio? I know a few of the stencils in other sets have similar affects if you don't use the default/blank one.

**Comment by softwarecraft** [comment]
Sorry no, I inherited the VSDX file from someone else

**Comment by David-Summers** [comment]
Hi @sandroasp 

Sharing my experience with this issue as I encountered the same problem with a lot of source SVG files where stroke was used to thicken a line to make it look like an object, or a really small view box was used. Visio does not handle this at all and this is the type of result you get.

As an example, I dragged the Azure AD risky sign in stencil object into a Page and it only displays a portion of the entire Icon. If you scale that icon up you get what appears on the right. I had to solve this by removing any viewbox elements and where stroke was used re-draw using an SVG editor. My result on the same icon is bottom left for reference. 

![image](https://user-images.githubusercontent.com/53208734/116200526-ca31a800-a77b-11eb-8bb4-3c3a8de9c0e7.png)

I spent many hours correcting or re-drawing source SVGs to get them to play nice with Visio. Feel free to check out my Repo and let me know what you think.

https://github.com/David-Summers/Azure-Design

**Comment by sandroasp** [comment]
Hi ,

Many people already report that issue. I'm using the latest version of Visio and I don't have that problem. Nevertheless, here is the solution:

Encountered the same problem (greyed out icons) in Visio Professional 2016. To fix this, you may either change to transparency for Line to 100% as earlier suggested or simply do the following:

Select icon --> Select shape --> Line --> "No Line"

(No Line = 100% transparency)

**Comment by sandroasp** [comment]
hope this fix the issue

**Comment by softwarecraft** [comment]
Your suggestion is a work around not a fix, please keep the issue open until the stencil is updated to implement the permanent fix

**Comment by sandroasp** [comment]
I don't have any problem reopening this issue, but as I told you, I don't have a way to try in Visio Professional 2016. I'm using Visio Professional 2019 and it's working fine.

You are welcome to fix this issue and contribute to this project.
