### ISSUE TITLE
SVG in Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio-master\Enterprise Integration\SVG

### ISSUE THREAD

**Issue by gerard10** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#31]
Hello.

I download de master and simply test de SVG files inside Enterprise Integration\SVG and it's not posible to view 

inside a brwoser.
I test with  Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio/AI and Machine Learning/SVG/AI-services.svg  and it works but another test with Databases and Analytics/SVG/Azure-Cache-for-Redis.svg doesn't work.

Please check the diference among diferent svg files in diferent directories to make it a valid SVG file.

In file API-Connections.svg with this header line works , I copy paste from 
https://upload.wikimedia.org/wikipedia/commons/f/fe/Minion_%28example%29.svg
works right
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 497.304 497.304" style="enable-background:new 0 0 497.304 497.304;" xml:space="preserve">

Thanks in advance.

**Comment by sandroasp** [comment]
I change all of the Enterprise Integration\SVG now they should work properly on the browser.

They didn't work properly on the browser but all of them are properly imported into Visio. Some of the SVG tart are presented well in the browser you cannot properly import them into Visio.
