### ISSUE TITLE
Azure Virtual Machines Scale Sets stencil

### ISSUE THREAD

**Issue by mattanknol** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#34]
I expected a stencil for Virtual Machine Scale Sets in the Microsoft Azure Stencils, but I couldn't find it. I did find the SVG icon in the icons map, but no stencil.

**Comment by sandroasp** [comment]
Just added that shape to the Microsoft Azure Stencils. Thanks for the warning
