### ISSUE TITLE
Shapes not appearing correctly

### ISSUE THREAD

**Issue by Caude123** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#38]
These are not displaying correctly in Visio 2016. They comes up as grey when put into the diagram. Is Visio 2016 supported? Any idea what the issue is?
Here is an example of the "user" shape.

![Screenshot 2021-05-13 105908](https://user-images.githubusercontent.com/61421973/118144429-74473c00-b3da-11eb-99d8-45bba663382e.jpg)

**Comment by sandroasp** [comment]
Hi Caude123,

Many people already report that issue. I'm using the latest version of Visio and I don't have that problem. Nevertheless, here is the solution: 

    Encountered the same problem (greyed out icons) in Visio Professional 2016. To fix this, you may either change to transparency for Line to 100% as earlier suggested, or simply do the following:
    
    Select icon --> Select shape --> Line --> "No Line"
    
    (No Line = 100% transparency)

**Comment by sandroasp** [comment]
I hope that solved your issue
