### ISSUE TITLE
Searching through local stencils

### ISSUE THREAD

**Issue by cveld** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#39]
I have added some stencils to the MyShapes folder and they are popping up in the shapes navigation. But when I try to use the search experience, Visio will not yield any result from these locally stored stencils. What am I doing wrong?
Using Visio 2019 MSO 32-bit.

**Comment by sumo300** [comment]
> I have added some stencils to the MyShapes folder and they are popping up in the shapes navigation. But when I try to use the search experience, Visio will not yield any result from these locally stored stencils. What am I doing wrong?
> Using Visio 2019 MSO 32-bit.

I think I had the same issue and discovered that I did not have Windows indexing the stencils folder for search.  Since then, search inside of Visio for keywords at appear in the name of the stencil seem to find them.  For example, I just tested searching for `MySQL` and it found several.

**Comment by sandroasp** [comment]
I'm almost sure that this is not an issue with my stencils but a VISIO annoying issue/limitation. I had in the past put the search working by following similar instructions here: https://social.technet.microsoft.com/Forums/lync/en-US/9d6e64ce-b9d6-4493-ade4-81c7a0dd4c2a/visio-2013-search-local-shapes-not-working-?forum=visiogeneral

With all Office applications closed, kick off a complete rebuild of the index under the Advanced button of the Indexing options. When the Indexing is completely finished, open Windows Explorer, and browse to the Visio Content folder, and search for something like "car" - you should find several stencil files with that keyword. 

Then open Visio, and try the same keyword search.  You should also find several shapes with "car" as the keyword - probably around 25-30.
