### ISSUE TITLE
Stencils missing in 7.2.0

### ISSUE THREAD

**Issue by photon1503** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#40]
Hi,

in the latest release, some .vssx Files are missing, i.e. "MIS Azure Stencils.vssx" and others.

Version 7.2:
![image](https://user-images.githubusercontent.com/14548927/122884469-7d62eb80-d33e-11eb-8f7a-a18ec4c5744e.png)

Old version:
![image](https://user-images.githubusercontent.com/14548927/122884430-7340ed00-d33e-11eb-8347-45ecd82588c7.png)

**Comment by sandroasp** [comment]
Thanks for the warning. I update the release with the missing files

**Comment by photon1503** [comment]
thank you!!
