### ISSUE TITLE
Request to add the Dynamics 365 product icons

### ISSUE THREAD

**Issue by chrispiasecki** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#41]
EDIT: I just noticed you have already done this, I did not have the latest version :).

Would be great if the Dynamics 365 product icons could be added to this stencil pack!

I have tried creating Visio stencils with the SVGs provided by MSFT, but unfortunately most of the icons won't properly resize when using them. I presume this is just my inexperience with Visio so I am hoping this is something straightforward for someone like yourself.

Dynamics 365 Icons:
https://docs.microsoft.com/en-us/dynamics365/get-started/icons

**Comment by sandroasp** [comment]
yep... Dynamics 365 icons are ins the latest version
