### ISSUE TITLE
Cannot find Private Endpoint icon

### ISSUE THREAD

**Issue by modbase** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#46]
I've been looking for more than half an hour to find the Azure Private Endpoint icon, but simply can't find it anywhere. I know it exists, because I found the [svg file](https://github.com/sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio/blob/master/Azure/SVG/Private-Endpoints.svg) in the repo. 

The only icon I can find in the stencils is the Private Link Service one. 

![image](https://user-images.githubusercontent.com/1606383/156752441-b8975c47-a636-42e4-bfa5-47f4ec7a9c82.png)

Where exactly is the Private Endpoint one located?

**Comment by sandroasp** [comment]
You can find the Private Endpoint icon on the Microsoft Azure: Additional or Support
![image](https://user-images.githubusercontent.com/1318263/160496331-6b2e4f40-f416-4244-85f6-7ef277bf0119.png)

The icon has a new layout as you can see on the Azure Portal
![image](https://user-images.githubusercontent.com/1318263/160496507-c7c488a0-b7c1-42f1-b896-0dd0724884db.png)

**Comment by brianstringfellow** [comment]
I opened a similar issue on another shape. Here is a link to a note that may help others to quickly solve the problem.
https://github.com/sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio/issues/47#issuecomment-1082459835
