### ISSUE TITLE
Azure stencils corrupt

### ISSUE THREAD

**Issue by darrenjoycenz** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#51]
Hi. Trying to use Azure stencils, but visio reports it is corrupt.

![image](https://github.com/sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio/assets/16659400/a729ae99-0eef-418a-99a1-30213a48ed89)

version 8.0.1 stencils.

**Comment by sandroasp** [comment]
humm... going to upload the files again

**Comment by sandroasp** [comment]
It should be solved now
