### ISSUE TITLE
Subscription and Management Group Icons

### ISSUE THREAD

**Issue by ChristopherGLewis** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#6]
Can you add the Azure Subscription and Management Group icons?

These are PNG's but I'm specifically hunting for the color SVG's on the portal so they size correctly.

![image](https://user-images.githubusercontent.com/8505994/57139483-fed01c00-6d7a-11e9-8fe0-bfa5f0c2e700.png)

![image](https://user-images.githubusercontent.com/8505994/57139468-f7107780-6d7a-11e9-8e80-047d393e6af6.png)

**Comment by sandroasp** [comment]
Done!

**Comment by FHPIENAAR** [comment]
Brilliant, been looking for these!
