### ISSUE TITLE
Microsoft Dynamics 

### ISSUE THREAD

**Issue by Kilsgaard** [sandroasp/Microsoft-Integration-and-Azure-Stencils-Pack-for-Visio#8]
Thanks for all the stencils :D

I would be fantastic with the Dynamics icons also.

Dynamics CRM
Dynamics BC
Dynamics 365
etc,

**Comment by sandroasp** [comment]
There are some Dynamics stencils in the resource: MIS Apps and Systems Logo Stencils. But I will see what I can do in the future

**Comment by Kilsgaard** [comment]
Thanks :-)

**Comment by Huodong-Yuan** [comment]
> Thanks for all the stencils :D
> 
> I would be fantastic with the Dynamics icons also.
> 
> Dynamics CRM
> Dynamics BC
> Dynamics 365
> etc,

This is also what I am looking for. Thanks!

**Comment by jasonaalmeida** [comment]
Would be great if we can get stencils to the various D365 apps included in this pack (customer engagement apps + finops + BC, etc)

**Comment by sandroasp** [comment]
Can you guys point me to some samples, I will try to do my best to add it in new releases

**Comment by jasonaalmeida** [comment]
here's what they look like - https://cloudblogs.microsoft.com/dynamics365/it/2019/10/04/the-dynamics-365-marketing-2019-release-wave-2-update-is-rolling-out-starting-now/

They used to be on the Microsoft docs page for D365, but can't seem to find them anymore. Here's another place i managed to find them - https://community.dynamics.com/nav/b/totovicnavblog/posts/new-dynamics-365-logos

**Comment by sandroasp** [comment]
Unfortunately, I cannot find these icons anywhere. The only ones I have is Forms, Power BI, Power Apps and Power Automate
